### ISSUE TITLE
The problem of taking the value of M

### ISSUE THREAD

**Issue by zkzhu-pro** [mcaceresb/stata-honestdid#15]
What should I consider about the value of M. Does M have to be equal to 1 or 2?  I have applied this method. But when M_hat is greater than 1, the lower bound is less than zero, does this mean that DID results are not very good? the image is as follows:
![MM](https://user-images.githubusercontent.com/59312438/231806295-2252a525-3b90-4d96-85e4-d0d3e5759bfa.jpg)
Thank you for your help！

**Comment by jonathandroth** [comment]
Hi, assuming that this is using the relative magnitudes restriction (the
default in Stata), this suggests that the significance of the result is
robust to allowing for violations of parallel trends as large as about 0.8
times the *largest *violation of parallel trends in the pre-treatment.
