### ISSUE TITLE
Using pystata to call honesdid in Python reports an error

### ISSUE THREAD

**Issue by mingzidouzhemenanqi** [mcaceresb/stata-honestdid#16]
Thanks for this great package!

I use the package to do some example for experiment. In order to easily organize the results, I chose to use pystata to call honesdid in Python. But something strange happened. I can run honesdid in stata, but if I use pystata to call honesdid, python raise error. 
![py](https://github.com/mcaceresb/stata-honestdid/assets/53385563/2f72f860-1c72-435d-a543-5c774ee97e4b)

honesdid works fine in my stata
![stata](https://github.com/mcaceresb/stata-honestdid/assets/53385563/e1dcf2d6-457d-4f82-abed-086d5a219d3e)

At the same time, after I ran honesdid in stata, I did not find the storage location of the results. So I haven't found a way to export the results to excel in stata.

My envrioment: Win 10, stata18, anacanda (Python 3.10.9)

Please let me know if you need any other details.

Many thanks

**Comment by mcaceresb** [comment]
Do you mean the mata object is not created? You can save the results from mata into excel in a number of ways, but LMK if you can't find the mata results.

PS: I haven't used pystata; I tried setting it up and got errors just setting it up. So without more context I wouldn't be able to even nake an educated guess as to what the issue is.

**Comment by mingzidouzhemenanqi** [comment]
Thank a lot! I will try LMK

**Comment by mingzidouzhemenanqi** [comment]
Sorry to bother you again.....

After running the honesdid command in stata, I still can't find a way to export the results to excel.

I tried some command like esttab, outreg2 to export the results of honesdid. But all of them exports the result of eventdd
![1](https://github.com/mcaceresb/stata-honestdid/assets/53385563/50ee9ac8-e4d6-41d7-9c9b-1a400b8775a2)

The results I want to export to Excel is:
![2](https://github.com/mcaceresb/stata-honestdid/assets/53385563/4b175c2f-4ef8-435b-b07d-56e42b25bbe8)

What commands do I need to use？

Many Thanks !

**Comment by mcaceresb** [comment]
@mingzidouzhemenanqi No worries. It's totally fine if you don't know mata; I think it's not immediately clear, I just didn't want to be redundant if the problem was something else.

Anyway, here's an example:

```stata
* Run the regression
* ------------------
local mixtape https://raw.githubusercontent.com/Mixtape-Sessions
use `mixtape'/Advanced-DID/main/Exercises/Data/ehec_data.dta, clear
keep if (year < 2016) & (missing(yexp2) | (yexp2 != 2015))
gen byte D = (yexp2 == 2014)
gen `:type year' Dyear = cond(D, year, 2013)
reghdfe dins b2013.Dyear, absorb(stfips year) cluster(stfips) noconstant

* Run HonestDiD and put results into a matrix
* -------------------------------------------
honestdid, pre(1/5) post(7/8) mvec(0.5(0.5)2) nocoefplot
mata st_matrix("honesttest", `s(HonestEventStudy)'.CI)
matrix colnames honesttest = M lb ub
matlist honesttest, names(columns)

* Export just the matrix to excel
* -------------------------------
putexcel set honesttest.xlsx, modify sheet(honesttest)
putexcel A1 = matrix(honesttest), colnames
putexcel save
putexcel clear

* Export with additional info
* ---------------------------
mata st_numscalar("honestalpha",  `s(HonestEventStudy)'.options.alpha)
mata st_strscalar("honestmethod", `s(HonestEventStudy)'.options.method)
mata st_strscalar("honestDelta",  `s(HonestEventStudy)'.options.Delta)

putexcel set honesttest.xlsx, modify sheet(honesttest)
putexcel A1 = matrix(honesttest), colnames
putexcel A`=`:rowsof honesttest'+2' = "alpha"
putexcel A`=`:rowsof honesttest'+3' = "method"
putexcel A`=`:rowsof honesttest'+4' = "Delta"
putexcel B`=`:rowsof honesttest'+2' = honestalpha
putexcel B`=`:rowsof honesttest'+3' = honestmethod
putexcel B`=`:rowsof honesttest'+4' = honestDelta
putexcel save
putexcel clear
```

There's other ways but I hope that's a straightforward example. LMK if you have trouble modifying it for your particular use case.

**Comment by mingzidouzhemenanqi** [comment]
Thank you very much!!

I have successfully exported the data

Inspired by you, I will spend some time learning mata

Again, thank you very much!
