### ISSUE TITLE
Issue with one post-treatment period and RM restriction? 

### ISSUE THREAD

**Issue by jonathandroth** [mcaceresb/stata-honestdid#17]
Does the issue raised with the R package [here](https://github.com/asheshrambachan/HonestDiD/pull/50) also affect the Stata package?

**Comment by mcaceresb** [comment]
@jonathandroth Merged in #18. I also added a warning if sigma is not symm PSD.

Btw it seems that when it got an odd sigma, R computed quantiles by ignoring missing values, whereas Stata gave a missing value and let the rest of the function continue out as if the entire thing had failed. I'm taking about [this function](https://github.com/asheshrambachan/HonestDiD/blob/master/R/arp-nuisance.R#L351). As part of this PR I'm making both packages behave more similar to each other.

**Comment by jonathandroth** [comment]
Thanks, Mauricio! Just to make sure I understand, you're talking about a
case where the user-provided variance-covariance matrix has some entries =
NA? If so, I think in this case we should probably just throw an error.

**Comment by mcaceresb** [comment]
@jonathandroth No, I accidentally found some cases where the vcov matrix has all non-missing values but some iterations inside "find least favorable cv" fail. The function in R reports a quantile by dropping missings, basically, and now I'm doing the same here.

**Comment by jonathandroth** [comment]
Got it. The LF critical value runs ~1000 linear programs and I think
sometimes there is some numerical precision error such that these fail to
converge. Dropping the missings is fine with me.
