### ISSUE TITLE
Plans for ssc?

### ISSUE THREAD

**Issue by NickCH-K** [mcaceresb/stata-honestdid#19]
Hello,

I am planning to recommend this package in my book. Are there plans to upload the package to SSC, or should I direct people to the Github?

Thank you!

**Comment by NickCH-K** [comment]
Oh! My mistake. I was going off of the repo readme which only suggests the net install option from Github. Thank you!

**Comment by jonathandroth** [comment]
Thanks, Nick! Mauricio, can we update the README to mention ssc as well?
