### ISSUE TITLE
Sensitivity Analysis for Other Periods

### ISSUE THREAD

**Issue by wenddymacro** [mcaceresb/stata-honestdid#4]
hi guys, we are interested in the effect for the fourth period after treatment. our twfe event study plot:

![image](https://user-images.githubusercontent.com/50739376/198964609-7a29a080-6852-48f4-b69c-030cf98cff3f.png)

our code of honestdid :

`matrix l_vec=(0\0\0\0\1\0\0\0\0\0\0\0\0)

honestdid, l_vec(l_vec) pre(1/12) post(13/25) mvec(0(0.025)0.25)

local plotopts xtitle(Mbar) ytitle(95% Robust CI)
honestdid, cached coefplot `plotopts'`

the results:

![image](https://user-images.githubusercontent.com/50739376/198964789-df990f74-5adf-4e5f-a144-15bd058ba519.png)

why the original effect/CI(red line) is different from the effect in TWFE ?

any insights?

thanks in advanced.

**Comment by mcaceresb** [comment]
@wenddymacro What is

```
matrix list e(b)
```

?

**Comment by wenddymacro** [comment]
. mat list e(b)

e(b)[1,25]
Pre_2	Pre_3	Pre_4	Pre_5	Pre_6	Pre_7	Pre_8	Pre_9
y1   .22417568	-.37208402	-.6068593	-.47421248	-.50601109	-.54184265	-.68990523	-.87048126

Pre_10	Pre_11	Pre_12	Pre_13	Post0	Post1	Post2	Post3
y1  -1.4504416	-.11910901	-.28366669	.49299721	.53201816	.76635512	.63850458	.79138165

Post4	Post5	Post6	Post7	Post8	Post9	Post10	Post11
y1   1.3078362	.92813858	2.6659446	2.3487094	1.0566333	.59196122	.64191653	1.1827365

Post12
y1  -4.3573762

**Comment by wenddymacro** [comment]
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/50739376/199001953-bff255f4-92fa-46ab-b1c0-b081f005fb6d.png">

**Comment by mcaceresb** [comment]
@wenddymacro Can you copy/paste the output of

```stata
matrix list e(b)
mata rows(st_matrix("e(V)")), cols(st_matrix("e(V)"))
matrix l_vec=(0\0\0\0\1\0\0\0\0\0\0\0\0)
honestdid, l_vec(l_vec) pre(1/12) post(13/25) mvec(0 0.025)
mata `s(HonestEventStudy)'.CI
mata `s(HonestEventStudy)'.betahat
mata `s(HonestEventStudy)'.numPrePeriods
mata `s(HonestEventStudy)'.numPostPeriods
mata `s(HonestEventStudy)'.options.alpha
mata `s(HonestEventStudy)'.options.l_vec
mata `s(HonestEventStudy)'.options.Mvec
mata `s(HonestEventStudy)'.options.grid_lb
mata `s(HonestEventStudy)'.options.grid_ub
```

?

**Comment by wenddymacro** [comment]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/50739376/199018835-bc5e9cd8-074f-4bd9-809b-b28260f43bd4.png">
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/50739376/199018946-66b68304-4217-402d-b372-e25474369fab.png">
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/50739376/199019024-9e016726-924c-4267-9a78-6e49dc824014.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/50739376/199019089-45769ca1-41c5-4844-aa99-9fd08aeb8481.png">
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/50739376/199019179-9bd0d1ed-1616-4d2a-952a-fd238463cabf.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/50739376/199019231-6d1ac2f5-72fa-47e5-9a44-86616036c9f5.png">

**Comment by mcaceresb** [comment]
@wenddymacro That output looks correct to me; you ran

```stata
local plotopts xtitle(Mbar) ytitle(95% Robust CI)
honestdid, cached coefplot `plotopts'
```

after this and got the plot in your original comment?

**Comment by wenddymacro** [comment]
![image](https://user-images.githubusercontent.com/50739376/199020376-cb4e1125-989c-4d68-be81-ab0cbaecb27f.png)

the plot is ok, but why?

**Comment by mcaceresb** [comment]
@wenddymacro I am a bit confused about what you mean by "why"? I haven't been able to reproduce the original issue. It's possible there were mis-aligned runs of `honestdid` is the only thing that comes to mind, but can't say for sure.

In any case, it seems that re-running fixed whatever issue there was?

**Comment by wenddymacro** [comment]
sorry to confusing u. i am interested in the reason on the difference between the rerun result and the original plot

**Comment by mcaceresb** [comment]
@wenddymacro Right; I don't know the reason. In your original comment you said you ran

```
matrix l_vec=(0\0\0\0\1\0\0\0\0\0\0\0\0)
honestdid, l_vec(l_vec) pre(1/12) post(13/25) mvec(0 0.025)
local plotopts xtitle(Mbar) ytitle(95% Robust CI)
honestdid, cached coefplot `plotopts'
```

right? But right now as I was asking for debug info, you re-run that and got a different result. I don't know why running the same code twice would give you different results; it should always give you the same thing. Did you run the above code all at once to get the original plot?

**Comment by wenddymacro** [comment]
😂No, i ran 
```
matrix l_vec=(0\0\0\0\1\0\0\0\0\0\0\0\0)
honestdid, l_vec(l_vec) pre(1/12) post(13/25) mvec(0 0.025)
local plotopts xtitle(Mbar) ytitle(95% Robust CI)
honestdid, cached coefplot `plotopts'
```

got

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/50739376/199024151-3ba75a8c-f5ba-46e7-8fb3-93737e20eb60.png">

**Comment by mcaceresb** [comment]
@wenddymacro From a new Stata session, can you run

```
matrix l_vec=(0\0\0\0\1\0\0\0\0\0\0\0\0)
honestdid, l_vec(l_vec) pre(1/12) post(13/25) mvec(0(0.025)0.25)
local plotopts xtitle(Mbar) ytitle(95% Robust CI)
honestdid, cached coefplot `plotopts'

matrix l_vec=(0\0\0\0\1\0\0\0\0\0\0\0\0)
honestdid, l_vec(l_vec) pre(1/12) post(13/25) mvec(0 0.25)
local plotopts xtitle(Mbar) ytitle(95% Robust CI)
honestdid, cached coefplot `plotopts'
```

and report the output? All your plots look different, which doesn't really make sense, and while your latest note does look like a bug, it also seems unrelated to your original post.

**Comment by wenddymacro** [comment]
sorry to mislead u. i ran other code.

i reran the code in my original post to the right plot:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/50739376/199028352-3e5d6f3a-0a70-47d8-bb41-f2f4b3119d40.png">

**Comment by wenddymacro** [comment]
it seems that re-running fixed the issue
