### ISSUE TITLE
running honestdid with did_multiplegt

### ISSUE THREAD

**Issue by xhu3** [mcaceresb/stata-honestdid#9]
Thank you so much for developing this Stata command. When I used the provided code for did_multiplegt, it shows an error message: "matrix didmgt_results_no_avg not found". Should I use a different matrix name? Much appreciated!
<img width="612" alt="image" src="https://user-images.githubusercontent.com/122650794/212434800-6301dc87-20c2-47ac-857c-d425e934021d.png">

**Comment by mcaceresb** [comment]
@xhu3 Do you mean the commands in the README? What is the version of `did_multiplegt` that you are using?

**Comment by xhu3** [comment]
> 

Ah! That's why. Got `did_multiplegt` updated, and it runs perfectly now. Thank you!
